interFAX:
  scheme: "https"
  hostname: "rest.interfax.net"
  port: 443
  outboundFaxesEndpoint: "/outbound/faxes"
  outboundFaxesCompletedEndpoint: "/outbound/faxes/completed"
  outboundFaxesRecordEndpoint: "/outbound/faxes/%s"
  outboundFaxImageEndpoint: "/outbound/faxes/%s/image"
  outboundFaxesCancelEndpoint: "/outbound/faxes/%s/cancel"
  outboundSearchEndpoint: "/outbound/search"
  outboundDocumentsEndpoint: "/outbound/documents"